### PR TITLE
Lazyload arcpy

### PR DESCRIPTION
**Pull request by cwalv**

### CODE REVIEW

**Comment by lobsteropteryx** [comment]
Hi @cwalv, 

Finally had a chance to go through this; there's a lot of good stuff in here, but it's sort of a big PR.  We can discuss, but just a few notes:

* The CI job is failing on your branch; I haven't dug into the problem yet
* After looking at the lazy-loading code, I'm pretty apprehensive about it; seems like a lot of complexity to introduce for a small problem (basically just usage).  Are there use cases I'm missing?  I'm inclined to leave this out for now, unless there's a good reason to add it.
* It looks like you fixed a bug in the git module; it would be great to have that in its own issue/PR.
* Some of the changes here I've duplicated in the [extract-modules](https://github.com/gisinc/slap/tree/extract-modules) branch--namely pulling out a cli module, and getting rid of some of the class-level props that weren't being used.

**Comment by cwalv** [comment]
Yeah, I'll close this PR since I was unable to get the tests to pass in CI.  The problem is that the `lazyload`ing of `arcpy` conflicts with the `MagicMock` of it in the tests .. they do similar things and are stomping on each other.  All of the tests pass when they're ran individually with plain old `unittest`, but not at first when ran with `nosetests`.  In the later commits I was able to get them to pass when running `nosetests` on my machine, but it still fails in travis, and as you point out the benefit to the change is minimal anyway (i.e., all it buys you is being able to run something like `slap -h` and have it return without taking 10 seconds to import `arcpy` .. or raising an incoherent exception if it can't connect to the license server).

**Comment by cwalv** [comment]
The more general use case (beyond `slap -h`) is when there's an error in the config file, or any other condition where we can "fail fast" without hain to call into `arcpy`

**Comment by lobsteropteryx** [comment]
That's a good point...this has bitten me a few times.

Is it possible to do the import locally, within the `__init__` method of a class?  We could turn the esri wrapper module into a class, and do the import there?  Worth experimenting with, for sure.

**Pull request closed without merging**
